version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install requests -t .
      - >-
        aws cloudformation package --template template.yaml --s3-bucket
        codepipeline-us-west-1-166209559445 --output-template template-export.yaml
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
